import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "tailwind-styled-components"
import styles from '../styles/Login.module.css'

const Section = styled.section`
  min-width: 100vh;
  display: flex;
  flex-direction: column;
  flex-grow: 1;
`;

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
  <main>
    <article>
      <div className="phoneContainer">
          <div style={{margin: [27, 0, 0, 113]}}>
            <img src="images/phones/screenshot1.png"
            style={{height: 538.84, width: 250}}/>
          </div>
      </div>
      <div className="loginContainer">
        <div className="loginBox">
          <h1 className="headline sprite spriteHeadline">Instagram</h1>
          <div className="inputsContainer">
            <form action="/" method="get">
              <div className="inputs">
                <div className="inputContainer">
                  <div className="inputInner">
                    <label>
                      <span className="inputPlaceHolder">전화번호, 사용자 이름 또는 이메일</span>
                      <input autoCapitalize="off" autoCorrect="off" maxLength={75} type="text"></input>
                    </label>
                    <div></div>
                  </div>
                </div>
                <div className="inputContainer">
                  <div className="inputInner">
                    <label>
                      <span className="inputPlaceHolder">비밀번호</span>
                      <input></input>
                    </label>
                    <div></div>
                  </div>
                </div>
                <div className="loginButtonContainer">
                  <button className="loginButton">
                    <div className="loginButtonInner">로그인</div>
                  </button>
                </div>
                <div className="divider">
                  <div className="divLine"></div>
                  <div style={{margin: [0, 18]}}>또는</div>
                  <div className="divLine"></div>
                </div>
                <div className="fbLoginContainer">
                  <button className="fbLoginButton">
                    <span className="sprite fbIcon"></span>
                    <span  style={{color: #385185}}>Facebook으로 로그인</span>
                  </button>
                </div>
              </div>
              <a className="forgetPassword">비밀번호를 잊으셨나요?</a>
            </form>
          </div>
        </div>
        <div className="loginBox">
          <div>
            <p style={{color: rgba(38, 38, 38, 1), font-size: 14, margin: 15, text-align: center}}>
              계정이 없으신가요?
              <a style="color: #0095f6; text-decoration: none;">
                <span style="font-weight: 600">가입하기</span>
              </a>
            </p>
          </div>
        </div>
        <div>
          <p style="color: rgba(38, 38, 38, 1); font-size: 14px; margin: 10px 20px 10px 20px; text-align:center;">앱을 다운로드 하세요</p>
          <div style="justify-content: center; margin: 10px 0 10px 0; flex-direction:row;">
            <a style="margin-right: 8px; "><img alt="appstore"/ src="images/badges/android_playstore_badge.png"  style="height:40px;"></a>
            <a><img alt="playstore"/ src="images/badges/ios_appstore_badge.png" style="height:40px;"></a>
          </div>
        </div>
      </div>
    </article>
    <footer>
      <div
      style="background-color: rgba(var(--bg-default), 1); padding: 0 20px">
        <div
        style="margin-top:52px; flex: 0 0 auto; justify-content: flex-start; align-items: stretch;"> <!-- 하단 링크 모음 -->
          <div
          className="footerItemContainer">
            <div className="footerItem">
              Meta
            </div>
            <div className="footerItem">
              소개
            </div>
            <div className="footerItem">
              블로그
            </div>
            <div className="footerItem">
              채용 정보
            </div>
            <div className="footerItem">
              API
            </div>
          </div>
          <div
          className="footerItemContainer">
            <div className="footerItem">
              댄스
            </div>
            <div className="footerItem">
              식음료
            </div>
            <div className="footerItem">
              블로그
            </div>
            <div className="footerItem">
              채용 정보
            </div>
          </div>
        </div>
        <div style="margin: 12px 0; justify-content: center; flex-direction: row;">
          <div style="flex-direction: row; align-items: center; justify-content: center;">
            <span style="color: rgb(142, 142, 142); font-weight: 400; font-size: 12px;">한국어</span>
            <div style="margin-left: 4px;">
              <span style="display: inline-block; transform: rotate(180deg);">
                <svg style="display: block; position: relative; color: rgb(142, 142, 142); fill: rgb(142, 142, 142); height: 12; width: 12;">
                  <path d="M21 17.502a.997.997 0 01-.707-.293L12 8.913l-8.293 8.296a1 1 0 11-1.414-1.414l9-9.004a1.03 1.03 0 011.414 0l9 9.004A1 1 0 0121 17.502z"></path>
                </svg>
              </span>
            </div>
            <select style="position: absolute; height: 100%; width: 100%; opacity: 0;">
              <option>Afrikaans</option>
              <option>Deutsch</option>
              <option>English</option>
            </select>
          </div>
          <div style="margin-left: 16px; color: rgb(142, 142, 142); font-size: 12px;">
            © 2022 Instagram from Meta
          </div>
        </div>
      </div>
    </footer>
  </main>
</Section>
    </div>
  );
};

export default Home;
